### ISSUE TITLE
Quoting style by culture

### ISSUE THREAD

**Issue by ceruulean** [prosegrinder/python-narrative#8]
Is there a way to specify British quoting conventions? (uses single quotes instead of double)?

**Comment by davidlday** [comment]
Not today, but I'll look into adding it as a feature. Can you provide an example or a URL to an example?

**Comment by ceruulean** [comment]
> ‘Economic systems’, according to Professor White, ‘are an inevitable byproduct of civilization, and are, as John Doe said, “with us whether we want them or not”’.
--[British versus American style](https://www.thepunctuationguide.com/british-versus-american-style.html)

> “It was getting really cold,” he said, “and they were saying ‘When can we go back home?’”
> Jaya said, ‘They were getting really excited and were shouting “Come on!”’.
--[Cambridge Dictionary](https://dictionary.cambridge.org/grammar/british-grammar/punctuation)

**Comment by davidlday** [comment]
@ceruulean  Finally getting time to look at this. Currently, you can override the regex used by pass in a new one. So I'm adding BRITISH_DIALOGUE_RE to the package. Tests generally are passing, but I'm not convinced it's right. The final ".\n" from your sample text winds up a dialogue, but I'm having trouble wrapping my head around whether that's correct.

Take a look at PR #9 and if you have any thoughts or advice, would love to hear it. I should be able to pick up again tomorrow.

**Comment by davidlday** [comment]
closed by #9
